# Generated by Django 5.2.7 on 2025-11-11 17:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('matricula', models.CharField(max_length=7, unique=True)),
                ('cargo', models.CharField(max_length=30)),
                ('idade', models.IntegerField()),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Funcionarios', to='empresas.empresa', verbose_name='Empresa Contratante ')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Jornada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_entrada', models.DateTimeField(default=django.utils.timezone.now)),
                ('hora_saida', models.DateTimeField(blank=True, null=True)),
                ('horas_trabalhadas', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jornadas', to='funcionarios.funcionario')),
            ],
            options={
                'verbose_name': 'Jornada de Trabalho',
                'ordering': ['-horas_trabalhadas'],
            },
        ),
        migrations.AddIndex(
            model_name='funcionario',
            index=models.Index(fields=['cpf', 'matricula'], name='funcionario_cpf_4cf68f_idx'),
        ),
    ]
