# Generated by Django 5.2.7 on 2025-10-31 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contas', '0001_initial'),
        ('empresas', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('matricula', models.CharField(max_length=7, unique=True)),
                ('cargo', models.CharField(max_length=30)),
                ('idade', models.IntegerField()),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Funcionarios', to='empresas.empresa', verbose_name='Empresa Contratante ')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contas.user')),
            ],
            options={
                'indexes': [models.Index(fields=['cpf', 'matricula'], name='funcionario_cpf_4cf68f_idx')],
            },
        ),
    ]
