# Generated by Django 5.2.7 on 2025-10-29 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('matricula', models.IntegerField()),
                ('cargo', models.CharField(max_length=30)),
                ('idade', models.IntegerField()),
            ],
        ),
    ]
