# Generated by Django 5.2.7 on 2025-10-29 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='cpf',
            field=models.CharField(default=0, max_length=14),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='matricula',
            field=models.IntegerField(max_length=7),
        ),
    ]
