# Generated by Django 5.2.7 on 2025-10-29 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0003_alter_funcionario_matricula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='cpf',
            field=models.CharField(max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='matricula',
            field=models.CharField(max_length=7, unique=True),
        ),
    ]
