# Generated by Django 5.2.7 on 2025-10-29 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0004_alter_funcionario_cpf_alter_funcionario_matricula'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='funcionario',
            index=models.Index(fields=['cpf', 'matricula'], name='funcionario_cpf_4cf68f_idx'),
        ),
    ]
