# Generated by Django 5.2.7 on 2025-10-30 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
        ('funcionarios', '0005_funcionario_funcionario_cpf_4cf68f_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Funcionarios', to='empresas.empresa', verbose_name='Empresa Contratante '),
            preserve_default=False,
        ),
    ]
